name: Java CI

on:
  push:
    branches:
      - main  # Skift "main" til din hovedgren, f.eks. "master", hvis det er relevant

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build and test with Maven
        run: mvn -B clean test
