name: Java CI

on:
  push:
    branches:
      - master  # Skift "main" til din hovedgren, f.eks. "master", hvis det er relevant

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          architecture: 'x64'
          overwrite-settings: true

      - name: Build and test with Maven
        run: mvn test