name: Java CI with Maven and H2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Test with Maven
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_CONFIG_LOCATION: classpath:/application-test.properties
        run: |
          mvn -B clean test
