name: Java CI

on:
  push:
    branches:
      - master  # Skift "main" til din hovedgren, f.eks. "master", hvis det er relevant

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B clean test  # Kør Maven-testene